// Summariser — v1 advisory mode per CC compact API spike.
//
// Given a list of conversation turns + preservation rules, builds a
// compressed summary that:
//   - preserves the last `preserveLastTurns` verbatim (untouched)
//   - extracts and pins all docs/superpowers/specs/* paths when
//     `preserveSpecPaths === true`
//   - replaces the dropped middle with a structured summary that the
//     user can paste back after `/compact`.
//
// Contract:
//   summarise({ turns, preserveLastTurns, preserveSpecPaths, summariseFn })
//     turns:           [{role: "user"|"assistant", content: string, tokens?: number}]
//     preserveLastTurns: number
//     preserveSpecPaths: boolean
//     summariseFn:     async (turnsToCompress) => string
//                      Caller supplies the actual model call (e.g., haiku).
//                      Tests pass a deterministic mock.
//   Returns:
//     { summaryText, droppedTurnCount, preservedRefs[], tokensBefore, tokensAfterEstimate }

const SPEC_PATH_RE = /docs\/superpowers\/(?:specs|plans|research-notes)\/[\w.\-/]+\.md/g;

function tokenCount(turn) {
  if (typeof turn.tokens === "number") return turn.tokens;
  // Rough estimate: 3 bytes per token (mixed).
  const bytes = (turn.content ?? "").length;
  return Math.ceil(bytes / 3);
}

function extractSpecPaths(turns) {
  const set = new Set();
  for (const t of turns) {
    const text = t.content ?? "";
    const matches = text.match(SPEC_PATH_RE);
    if (matches) for (const m of matches) set.add(m);
  }
  return [...set];
}

export async function summarise({
  turns,
  preserveLastTurns = 6,
  preserveSpecPaths = true,
  summariseFn,
}) {
  if (!Array.isArray(turns)) throw new Error("turns must be array");
  if (typeof summariseFn !== "function") {
    throw new Error("summariseFn required (caller-supplied model call)");
  }
  const n = turns.length;
  if (n <= preserveLastTurns) {
    // Nothing to compress.
    return {
      summaryText: "",
      droppedTurnCount: 0,
      preservedRefs: preserveSpecPaths ? extractSpecPaths(turns) : [],
      tokensBefore: turns.reduce((s, t) => s + tokenCount(t), 0),
      tokensAfterEstimate: turns.reduce((s, t) => s + tokenCount(t), 0),
    };
  }
  const tail = turns.slice(n - preserveLastTurns);
  const head = turns.slice(0, n - preserveLastTurns);
  const refs = preserveSpecPaths ? extractSpecPaths(head) : [];

  const summaryBody = await summariseFn(head);

  const sections = [];
  sections.push("# Conversation summary (auto-generated by thrift summariser)");
  sections.push("");
  sections.push(`Compressed ${head.length} turns from the start of the conversation. ${tail.length} most recent turns preserved verbatim after this summary.`);
  if (refs.length > 0) {
    sections.push("");
    sections.push("## Spec / plan references (preserved verbatim)");
    sections.push("");
    for (const r of refs) sections.push(`- ${r}`);
  }
  sections.push("");
  sections.push("## Summary");
  sections.push("");
  sections.push(summaryBody);

  const summaryText = sections.join("\n");
  const tokensBefore = head.reduce((s, t) => s + tokenCount(t), 0);
  const tokensAfterEstimate = Math.ceil(summaryText.length / 3);

  return {
    summaryText,
    droppedTurnCount: head.length,
    preservedRefs: refs,
    tokensBefore,
    tokensAfterEstimate,
  };
}

// Default summariseFn that does dependency-free heuristic compression
// (no LLM call). Useful as a v1 fallback when no model is available.
// Reduces each turn to its first sentence + a "(role)" tag.
export function heuristicSummariseFn() {
  return async (turns) => {
    const lines = [];
    for (const t of turns) {
      const text = (t.content ?? "").trim();
      const firstSentence = text.split(/(?<=[.!?])\s+/)[0] || text.slice(0, 120);
      lines.push(`- (${t.role}) ${firstSentence}${firstSentence.length < text.length ? " …" : ""}`);
    }
    return lines.join("\n");
  };
}
