import { assertValidCapabilities } from "../lib/capabilities/schema.mjs";

export const CAPABILITIES = [
  {
    id: "agent-init",
    name: "Agent Init",
    command: "/agent-init",
    description: "Bootstrap project-local guidance, role personas, hooks, task ledger, and floor config.",
    inputs: { prompt: "optional project purpose", flags: ["--lite", "--lang", "--theme"] },
    outputs: { artifacts: ["root guidance", "role files", "policy hook", "task ledger"] },
    requiredHooks: ["context-mode-router", "agent-policy-hook"],
    requiredArtifacts: ["CLAUDE.md", "AGENTS.md", ".agent-all.json"],
    platformSupport: {
      claude: "native",
      codex: "native",
      copilot: "partial",
      cursor: "partial",
      gemini: "partial",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "agent-all",
    name: "Agent All",
    command: "/agent-all",
    description: "Plan, dispatch, gate, and optionally loop a PR-shipping implementation workflow.",
    inputs: { task: "free-form prompt or task doc", flags: ["--loop", "--qa", "--resume"] },
    outputs: { artifacts: [".agent-all-state.json", "PR body", "run logs"] },
    requiredHooks: ["agent-policy-hook", "interaction-log"],
    requiredArtifacts: [".agent-all.json", ".agent-all-state.json"],
    platformSupport: {
      claude: "native",
      codex: "partial",
      copilot: "partial",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "visual-qa",
    name: "Visual QA",
    command: "/visual-qa",
    description: "Crawl UI pages, exercise shallow interactions, capture screenshots, and produce visual verdicts.",
    inputs: { config: ".visual-qa.json", server: "baseUrl" },
    outputs: { artifacts: ["report.md", "report.html", "screenshots", "analysis JSON"] },
    requiredHooks: ["playwright-mcp"],
    requiredArtifacts: [".visual-qa.json", ".agent-skill/reports/visual-qa"],
    platformSupport: {
      claude: "native",
      codex: "partial",
      copilot: "partial",
      cursor: "partial",
      gemini: "partial",
      "vscode-copilot": "unsupported",
    },
  },
  {
    id: "thrift",
    name: "Thrift",
    command: "/thrift",
    description: "Reduce long-session cost through context-mode routing, prompt-cache priming, and audits.",
    inputs: { config: ".thrift.json" },
    outputs: { artifacts: ["thrift audit", "session summary"] },
    requiredHooks: ["session-end-audit"],
    requiredArtifacts: [".thrift.json"],
    platformSupport: {
      claude: "native",
      codex: "partial",
      copilot: "partial",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "explore",
    name: "Explore",
    command: "/explore",
    description: "Build and query a codebase map with dependency and symbol lookup helpers.",
    inputs: { query: "where/deps query" },
    outputs: { artifacts: [".explore-cache", "map reports"] },
    requiredHooks: [],
    requiredArtifacts: [".explore-cache"],
    platformSupport: {
      claude: "native",
      codex: "unsupported",
      copilot: "unsupported",
      cursor: "unsupported",
      gemini: "unsupported",
      "vscode-copilot": "unsupported",
    },
  },
  {
    id: "debug",
    name: "Debug",
    command: "/debug",
    description: "Reproduce, isolate, hypothesize, verify, and log a systematic debugging session.",
    inputs: { failingCommand: "command or failure subject" },
    outputs: { artifacts: [".debug-state.json", ".agent-skill/reports/debug"] },
    requiredHooks: [],
    requiredArtifacts: [".debug-state.json", ".agent-skill/reports/debug"],
    platformSupport: {
      claude: "native",
      codex: "partial",
      copilot: "unsupported",
      cursor: "unsupported",
      gemini: "unsupported",
      "vscode-copilot": "unsupported",
    },
  },
  {
    id: "agent-handoff",
    name: "Agent Handoff",
    command: "/agent-handoff",
    description: "Generate resumable handoff and new-session prompt artifacts for in-progress tasks.",
    inputs: { taskPath: ".agent-skill/tasks/<id>.md", flags: ["--strict", "--dry-run"] },
    outputs: { artifacts: [".handoff.md", ".session.md", "interactions.jsonl"] },
    requiredHooks: ["interaction-log"],
    requiredArtifacts: [".agent-skill/tasks", ".agent-skill/handoff", ".agent-skill/runs/handoff/interactions.jsonl"],
    platformSupport: {
      claude: "native",
      codex: "partial",
      copilot: "soft",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "interaction",
    name: "Interaction",
    command: "agent-interaction/v1",
    description: "Normalize decisions, confirmations, resume prompts, budget warnings, and blocked states.",
    inputs: { schema: "agent-interaction/v1" },
    outputs: { artifacts: ["interactions.jsonl", "state.interactions"] },
    requiredHooks: ["interaction-log"],
    requiredArtifacts: [".agent-skill/runs/<run-id>/interactions.jsonl"],
    platformSupport: {
      claude: "native",
      codex: "partial",
      copilot: "partial",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "policy-hook",
    name: "Policy Hook",
    command: "agent-policy-event/v1",
    description: "Evaluate loop, shell, verification, reviewer-audit, spawn, and non-TTY decision policies.",
    inputs: { schema: "agent-policy-event/v1" },
    outputs: { artifacts: ["policy-log.jsonl", "hook decisions"] },
    requiredHooks: ["agent-policy-hook"],
    requiredArtifacts: [".agent-skill/runs/<run-id>/policy-log.jsonl"],
    platformSupport: {
      claude: "native",
      codex: "partial",
      copilot: "partial",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "cost-telemetry",
    name: "Cost Telemetry",
    command: "agent-cost-telemetry/v1",
    description: "Normalize reported or estimated token/cost usage, enforce budget thresholds, and persist run cost summaries.",
    inputs: { schema: "agent-cost-telemetry/v1", config: ".agent-all.json telemetry.cost" },
    outputs: { artifacts: ["cost-telemetry.jsonl", "state.costTelemetry", "task cost summary"] },
    requiredHooks: ["policy-hook"],
    requiredArtifacts: [".agent-skill/runs/<run-id>/cost-telemetry.jsonl"],
    platformSupport: {
      claude: "partial",
      codex: "partial",
      copilot: "partial",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "verification-adapter",
    name: "Verification Adapter",
    command: "verification-adapter",
    description: "Represent web, CLI, API, data, SQL, and batch completion evidence behind a common verification result contract.",
    inputs: { plan: "adapter-specific verification plan", adapters: ["verify:web-ui", "verify:cli", "verify:api-contract", "verify:notebook-data", "verify:sql-db", "verify:batch-job"] },
    outputs: { artifacts: [".agent-skill/runs/<run-id>/verification-evidence.jsonl", "break-condition summary"] },
    requiredHooks: ["verification-before-completion"],
    requiredArtifacts: [".agent-skill/runs/<run-id>/verification-evidence.jsonl"],
    platformSupport: {
      claude: "partial",
      codex: "partial",
      copilot: "soft",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "security-redaction",
    name: "Security Redaction",
    command: "agent-redaction-scan/v1",
    description: "Detect, mask, audit, and block secret/privacy candidates before control-plane artifacts are persisted or shared.",
    inputs: { artifacts: ["handoff", "session prompt", "reports", "logs", "PR body"], policy: ".agent-skill/policy.json security.redaction" },
    outputs: { artifacts: ["redaction-audit.jsonl", "redacted artifact content"] },
    requiredHooks: ["policy-hook"],
    requiredArtifacts: [".agent-skill/runs/<run-id>/redaction-audit.jsonl"],
    platformSupport: {
      claude: "partial",
      codex: "partial",
      copilot: "soft",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
  {
    id: "data-runner",
    name: "Data Runner",
    command: "/data-runner",
    description: "Plan notebook, SQL, artifact diff, and data handoff verification through agent-all data adapters.",
    inputs: { taskPath: ".agent-skill/tasks/<id>.md", modes: ["notebook", "sql", "artifact-diff", "handoff"] },
    outputs: { artifacts: ["verification-evidence.jsonl", "data artifacts", "handoff evidence"] },
    requiredHooks: ["policy-hook", "verification-adapter"],
    requiredArtifacts: [".agent-skill/tasks/_template.md", ".agent-skill/runs/<run-id>/verification-evidence.jsonl"],
    platformSupport: {
      claude: "native",
      codex: "soft",
      copilot: "soft",
      cursor: "soft",
      gemini: "soft",
      "vscode-copilot": "soft",
    },
  },
];

assertValidCapabilities(CAPABILITIES);

export function capabilityById(id) {
  return CAPABILITIES.find((capability) => capability.id === id) ?? null;
}
